static function testing( first_arg, second_arg )
{
	for each( a in [ 1, 2, 3, 4, 5, 9 ] ){
		show a;
	}
	foreach( b in { "a": 1, 1 + 1 : Foo(), Foo() : "Me" } ){
		show b.key();
		show b.value();
	}
	
	for each( s in {} ){}
	foreach( iter in [] ){
		// do nothing
	}
	var c = @{ return @( a ){ return 12 * first_arg + second_arg; }; };
	show c()( 15 );
}

function main()
{
	c = 12;
	do {
		testing( c , c + 1 );
		--c;
	} while( c <= 1 );
	c += 10;
	while( c <= 100 ){
		show c;
		c = c + 2;
	}
	show testing( c, 11 );
}
