# ARGS=-O3 -pthread -Wall -Wno-unused-function
ARGS=-g -D_DEBUG -D_OSX -Wall -Wno-unused-function

CC=g++
SRC=classes.o parser.o scanner.o tree.o emitter.o memory.o runtime.o substance.o 
EXE=subc

$(EXE): $(SRC)
	$(CC) -m64 -o $(EXE) $(SRC) $(OBJ_LIBS) 
#	$(CC) -m64 -o $(EXE) $(SRC) $(OBJ_LIBS) 

%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 

clean:
	rm -f $(EXE).exe $(EXE) *.exe *.a *.o *~

